[package]
name = "amber-json5"
version = "0.1.0"
edition = "2024"

[dependencies]
json5 = "1.3.0"
miette = { workspace = true }
pest = "2.8.4"
pest_derive = "2.8.4"
serde = { workspace = true }
serde_path_to_error = "0.1.20"

[dev-dependencies]
serde_derive = "1"
serde_json = { workspace = true }
