[package]
name = "amber-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "amber"
path = "src/main.rs"

[dependencies]
amber-compiler = { workspace = true }
amber-manifest = { workspace = true }
amber-resolver = { workspace = true }
clap = { version = "4.5.46", features = ["derive"] }
miette = { workspace = true, features = ["fancy"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
url = { workspace = true }

[dev-dependencies]
similar = "2.7.0"
strip-ansi-escapes = "0.2"
tempfile = { workspace = true }
