[package]
name = "amber-manifest"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
json5 = "0.4.1"
jsonschema = { version = "0.37.4", default-features = false }
semver = { version = "1.0.27", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
serde_with = "3.16.1"
shlex = "1.3.0"
thiserror = "2.0.9"
url = { version = "2.5.7", features = ["serde"] }
