name: amber-publish

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/amber-node
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=refs/heads/${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=refs/heads/${{ github.ref_name }}
      - name: Configure sidecar tags
        id: sidecar_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/amber-sidecar
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - name: Build and push sidecar
        uses: docker/build-push-action@v5
        with:
          context: docker/amber-sidecar
          file: docker/amber-sidecar/Dockerfile
          push: true
          tags: ${{ steps.sidecar_meta.outputs.tags }}
          labels: ${{ steps.sidecar_meta.outputs.labels }}
          cache-from: type=gha,scope=refs/heads/${{ github.ref_name }}-sidecar
          cache-to: type=gha,mode=max,scope=refs/heads/${{ github.ref_name }}-sidecar
      - name: Configure helper tags
        id: helper_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/amber-helper
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - name: Build and push helper
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/amber-compose-helper/Dockerfile
          push: true
          tags: ${{ steps.helper_meta.outputs.tags }}
          labels: ${{ steps.helper_meta.outputs.labels }}
          cache-from: type=gha,scope=refs/heads/${{ github.ref_name }}-helper
          cache-to: type=gha,mode=max,scope=refs/heads/${{ github.ref_name }}-helper
